version: '3'

services:
  db:
    image: postgres:alpine3.18
    container_name: cars_db
    build:
      context: .
    ports:
      - "5429:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=cars


  redis:
    image: redis:alpine3.19
    container_name: redis
    build:
      context: .
    ports:
      - 6379:6379