# Generated by Django 4.1.7 on 2023-05-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_list', '0004_alter_transport_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='is_booked',
            field=models.BooleanField(default=False),
        ),
    ]
